version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  # ================================= Bot =====================================
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    environment:
      - MAX_TYPING_TIME=3
      - MIN_TYPING_TIME=1
      - WORDS_PER_SECOND_TYPING=10
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ADMIN_USERNAME=admin
      - ROCKETCHAT_ADMIN_PASSWORD=admin
      - ROCKETCHAT_BOT_USERNAME=bia
      - ROCKETCHAT_BOT_PASSWORD=biabot
      - DEFENSORIA_TOKEN=token

      # Should be set to 'production' or 'beta' or 'dev'
      - ENVIRONMENT_NAME=beta
      # Last commit hash using this command: git rev-parse HEAD
      - BOT_VERSION=last-commit-hash

      # Analytics config
      - ENABLE_ANALYTICS=True
      - ELASTICSEARCH_URL=10.92.1.101

      # HTTP login on elasticsearch
      - ELASTICSEARCH_USER=defensoria
      - ELASTICSEARCH_PASSWORD=defensoria
      - ELASTICSEARCH_HTTP_SCHEME=http
      - ELASTICSEARCH_PORT=9292
    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
    volumes:
      - ./bot:/bot
      - ./scripts:/scripts

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
      - ./bot/Makefile:/bot/Makefile
    command: "make run-actions"

  # =============================== Notebooks =================================
  notebooks:
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    volumes:
      - ./bot:/work/bot
      - ./notebooks:/work/notebooks
    ports:
      - 8888:8888
