policies:
  - name: KerasPolicy
    epochs: 7
    batch_size: 10
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
          - name: LabelTokenizerSingleStateFeaturizer
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
  - name: MemoizationPolicy
    max_history: 3
